name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install dependencies
        run: |
          git clone https://github.com/online-judge-tools/verification-helper.git
          cd verification-helper
          sed -i "s/pathlib\.Path(path)/pathlib.Path(item)/" onlinejudge_verify/languages/nim.py
          python setup.py install
          pip3 install online-judge-verify-helper

        # run: pip3 install -U online-judge-verify-helper
      # required only if you want to verify C# script files
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.101"
      - name: Install dependencies (C#)
        run: dotnet tool install -g dotnet-script && echo ::add-path::$HOME/.dotnet/tools

      # required only if you want to verify Nim code
      - name: Install dependencies (Nim)
        run: sudo apt install nim

      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: oj-verify all
